export const Types = {
  AUTHENTICATE: 'AUTHENTICATE',
  REGISTER: 'REGISTER',
  VERIFY_EMAIL: 'VERIFY_EMAIL',
  REMOVE_AUTH: 'REMOVE_AUTH',
  GET_MY_PROFILE: 'GET_MY_PROFILE',
  ADD_AUTH: 'ADD_AUTH'
}
